---
apiVersion: v1 
kind: Service 
metadata: 
  name: redis-proxy
  namespace: default
  labels:
    app: redis-proxy
spec: 
  type: ClusterIP
  selector: 
    app: redis-proxy
  ports: 
  - port: 6379 
    targetPort: 6379
